apiVersion: v1
kind: Namespace
metadata:
  labels:
    kubernetes.io/metadata.name: tomcat
  name: tomcat
spec:
  finalizers:
  - kubernetes
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: tomcat
  name: tomcat
  namespace: tomcat
spec:
  selector:
    matchLabels:
      app: tomcat
  template:
    metadata:
      labels:
        app: tomcat
    spec:
      containers:
      - image: shryu1/tomcat:latest
        imagePullPolicy: IfNotPresent
        name: tomcat
        ports:
        - containerPort: 8080
          protocol: TCP
        resources: {}
      imagePullSecrets:
      - name: docker
#     nodeSelector:
#       key: worker2
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: tomcat
  name: tomcat-svc
  namespace: tomcat
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: tomcat
  type: ClusterIP
status:
  loadBalancer: {}
